name: common_utils2
description: A comprehensive Flutter utilities package with 24+ utilities for rapid app development. Includes banking, currency conversion, networking, and more.
version: 2.0.0
homepage: https://github.com/mhista/common_utils
repository: https://github.com/mhista/common_utils
issue_tracker: https://github.com/mhista/common_utils/issues
documentation: https://github.com/mhista/common_utils/wiki

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  injectable: ^2.7.1+4
  # HTTP & Network
  dio: ^5.9.1
  connectivity_plus: ^7.0.0

  
  # Storage
  shared_preferences: ^2.2.2
  hive_flutter: ^1.1.0

  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Device Info
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
    
  # Logging (Talker)
  talker: ^5.1.13
  talker_dio_logger: ^5.1.13
  talker_flutter: ^5.1.13
  talker_bloc_logger: ^5.1.13

  
  # Image Handling
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  
  # File Handling
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Encryption & Security
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # Formatting
  intl: ^0.20.2

  # notifications
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0

  # storage
  flutter_secure_storage: ^10.0.0
  video_player: ^2.11.0
  chewie: ^1.13.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  visibility_detector: ^0.4.0+2
  permission_handler: ^12.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  pdfx: ^2.9.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  # bloc_test: ^10.0.0
  # pdf_render: ^1.4.7


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0


flutter:

